responses = {
    "hello": "Hello! How can I assist you today?",
    "how are you?": "I'm just a chatbot, but I'm here to help you!",
    "what is your name?": "I am a simple chatbot created to assist you.",
    "what can you do?": "I can answer your questions and have a conversation with you.",
    "thank you": "You're welcome! If you have any more questions, feel free to ask.",
    "what is the weather like?": "I'm sorry, I don't have access to real-time weather information. You can check a weather website or app for the latest updates.",
    "help": "Sure! You can ask me anything or just have a chat with me.",
    "bye": "Goodbye! Have a great day!"
}

while True:
    user_input = input("You: ").lower()
    if user_input == "bye":
        print("Chatbot: " + responses["bye"])
        break
    elif user_input in responses:
        print("Chatbot: " + responses[user_input])
    else:
        print("Chatbot: I'm sorry, I don't understand that. Can you please rephrase?")
        
        
        
"""

responses = {
    "hello": "Hello! Welcome to our store. How can I assist you today?",
    "how are you?": "I'm just a chatbot, but I'm here to help you shop!",
    "what is your name?": "I am your shopping assistant chatbot.",
    "what can you do?": "I can help you browse products, track orders, and answer your questions.",
    "thank you": "You're welcome! Happy to assist you anytime.",
    "help": "Sure! You can ask me about products, orders, payments, or anything related to shopping.",
    "bye": "Goodbye! Have a wonderful shopping experience.",
    "show me products": "Sure! What type of products are you looking for?",
    "track my order": "Please provide your order ID, and I’ll check the status for you.",
    "return policy": "Our return policy allows returns within 30 days of purchase.",
    "refund policy": "Refunds are processed within 5–7 business days after approval.",
    "shipping options": "We offer standard, express, and same-day delivery depending on your location.",
    "payment methods": "You can pay using credit cards, debit cards, PayPal, or digital wallets.",
    "discounts": "Yes! We often have discounts and promotions. Would you like to see current offers?",
    "offers": "Here are our latest deals and offers available today.",
    "wishlist": "You can add items to your wishlist for future purchase.",
    "cart": "Would you like me to show you what’s currently in your cart?",
    "checkout": "To checkout, please confirm your shipping address and payment method.",
    "cancel order": "Please provide your order ID, and I’ll help you cancel it if possible.",
    "order status": "Can you share your order ID so I can check the status?",
    "delivery time": "Delivery usually takes 3–5 business days depending on your location.",
    "express delivery": "Express delivery is available for select products at an extra charge.",
    "same-day delivery": "Same-day delivery is available in certain cities. Would you like me to check?",
    "international shipping": "Yes, we ship internationally. Shipping costs vary by country.",
    "product availability": "Please tell me the product name, and I’ll check if it’s in stock.",
    "out of stock": "This product is currently out of stock. Would you like me to notify you when it’s available?",
    "new arrivals": "Here are the latest arrivals in our store.",
    "best sellers": "These are our most popular products right now.",
    "featured products": "Here are some featured products you might like.",
    "categories": "We have categories like electronics, fashion, home, and more. Which interests you?",
    "electronics": "We have phones, laptops, cameras, and more in electronics.",
    "fashion": "Our fashion section includes clothing, shoes, and accessories.",
    "home appliances": "We offer kitchen appliances, cleaning devices, and more.",
    "beauty products": "We have skincare, makeup, and personal care items.",
    "sports equipment": "We stock fitness gear, sportswear, and accessories.",
    "toys": "We have toys for kids of all ages.",
    "books": "Browse our wide collection of books across genres.",
    "gift cards": "You can purchase gift cards for friends and family.",
    "membership": "Our membership program offers exclusive discounts and free shipping.",
    "loyalty points": "You earn points with every purchase that can be redeemed later.",
    "customer support": "You can reach customer support via chat, email, or phone.",
    "contact us": "You can contact us through our support page or helpline.",
    "store hours": "Our online store is open 24/7!",
    "physical store": "We also have physical stores. Would you like me to locate one near you?",
    "store locator": "Please share your city, and I’ll find the nearest store.",
    "order history": "You can view your past orders in your account dashboard.",
    "invoice": "Would you like me to generate an invoice for your order?",
    "download receipt": "You can download your receipt from your account.",
    "track shipment": "Please provide your tracking number to check shipment status.",
    "delivery charges": "Delivery charges depend on your location and shipping method.",
    "free shipping": "We offer free shipping on orders above a certain amount.",
    "minimum order": "Some offers require a minimum order value.",
    "bulk orders": "We provide discounts on bulk purchases.",
    "wholesale": "Wholesale options are available for certain products.",
    "return process": "To return a product, please initiate a request from your account.",
    "exchange policy": "You can exchange products within 30 days of purchase.",
    "damaged product": "We’re sorry! Please report the issue, and we’ll arrange a replacement.",
    "wrong item": "If you received the wrong item, we’ll help you return it and send the correct one.",
    "order confirmation": "You’ll receive an email confirmation after placing your order.",
    "order cancellation": "Orders can be canceled before they are shipped.",
    "pre-order": "Some products are available for pre-order. Would you like details?",
    "backorder": "Backordered items will ship once they’re back in stock.",
    "subscription": "We offer subscription services for regular deliveries.",
    "newsletter": "Would you like to subscribe to our newsletter for updates?",
    "sale": "Our seasonal sale is live now! Check out the discounts.",
    "clearance": "Clearance items are available at huge discounts.",
    "limited edition": "We have exclusive limited-edition products available.",
    "gift wrapping": "Gift wrapping is available at checkout.",
    "personalized gifts": "We offer personalized gift options. Would you like to explore?",
    "recommendations": "Based on your browsing, here are some product recommendations.",
    "similar products": "Here are products similar to the one you viewed.",
    "compare products": "You can compare product features side by side.",
    "reviews": "Would you like to read customer reviews for this product?",
    "ratings": "This product has a rating of 4.5 stars.",
    "seller info": "You can view seller details on the product page.",
    "secure payment": "All payments are processed securely.",
    "emi options": "We offer EMI options on select products.",
    "cod": "Cash on delivery is available in certain locations.",
    "wallet balance": "You can use your wallet balance during checkout.",
    "coupons": "Apply coupons at checkout to get discounts.",
    "promo code": "Do you have a promo code to apply?",
    "gift voucher": "Gift vouchers can be redeemed during checkout.",
    "track return": "Please provide your return request ID to track status.",
    "customer feedback": "We value your feedback. Would you like to share your experience?",
    "complaint": "We’re sorry for the inconvenience. Please describe your issue.",
    "support ticket": "You can raise a support ticket from your account.",
    "live chat": "Our live chat support is available 24/7.",
    "call support": "You can call our helpline for assistance.",
    "email support": "You can email us at support@example.com.",
    "privacy policy": "You can read our privacy policy on our website.",
    "terms of service": "Our terms of service are available online.",
    "account": "You can manage your account settings from the dashboard.",
    "login": "Please log in to access your account.",
    "signup": "You can sign up to create a new account.",
    "forgot password": "Click on ‘Forgot Password’ to reset your password.",
    "update profile": "You can update your profile details anytime.",
    "delete account": "You can request account deletion from settings.",
    "security": "We use advanced security measures to protect your data.",
    "two-factor authentication": "Enable two-factor authentication for extra security.",
    "notifications": "You can manage your notification preferences in settings.",
    "language": "You can change the language from your account settings.",
    "currency": "Prices can be displayed in different currencies.",
    "location": "Please share your location for better recommendations.",
    "app": "Download our mobile app for easier shopping.",
    "social media": "Follow us on social media for updates.",
    "blog": "Check out our blog for shopping tips and trends.",
    "community": "Join our community forum to connect with other shoppers."
}
"""